# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfcvarSec < Formula
  desc "The tfcvar-sec is a tool that scanns Terraform Cloud for insecure terraform/enviroment variables."
  homepage "https://github.com/ausmartway/tfcvar-sec"
  version "0.2.6"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v0.2.6/tfcvar-sec_0.2.6_darwin_x86_64.tar.gz"
      sha256 "2ee07918de226bcd5e621b575641fd95de133f3c5cd353bcabb5a11e1987eb0b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ausmartway/tfcvar-sec/releases/download/v0.2.6/tfcvar-sec_0.2.6_linux_x86_64.tar.gz"
      sha256 "f75f66f897aa10c55d3d4a9c525030086927db2cd5524672a0a9ab25122029b2"
    end
  end

  def install
    bin.install "tfcvar-sec"
  end

  def caveats; <<~EOS
    Type 'tfcvar-sec scan' on your command line.
  EOS
  end

  test do
    system "#{bin}/tfcvar-sec --version"
  end
end
